### ISSUE TITLE
Project root directory not found. Indicators: ['.project-root']

### ISSUE THREAD

**Issue by qy0720** [TencentARC/SEED-Story#15]
**I missed a tricky problem, when I ran python3 src/inference/gen_george.py, mistake happened as follows.**

Traceback (most recent call last):
  File "/mnt/bn/qy-dcar-valume/SEED-Story/src/inference/vis_george_sink.py", line 15, in <module>
    pyrootutils.setup_root(__file__, indicator='.project-root', pythonpath=True)
  File "/mnt/bn/qy-dcar-valume/anaconda3/envs/seed/lib/python3.10/site-packages/pyrootutils/pyrootutils.py", line 151, in setup_root
    path = find_root(search_from, indicator)
  File "/mnt/bn/qy-dcar-valume/anaconda3/envs/seed/lib/python3.10/site-packages/pyrootutils/pyrootutils.py", line 73, in find_root
    raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
FileNotFoundError: Project root directory not found. Indicators: ['.project-root']

**Comment by AndysonYs** [comment]
Hi! You can run `touch .project-root` in the project root directory to fix this.

**Comment by qy0720** [comment]
Thank you for your reply. I have run it successfully. It is an interesting and great work.

**Comment by zzddwyff** [comment]
"run touch .project-root in the project root directory to fix this"
how to do it
