### ISSUE TITLE
image_root = 'data/image/george_full'

### ISSUE THREAD

**Issue by zzddwyff** [TencentARC/SEED-Story#28]
where is george_full?

**Comment by AndysonYs** [comment]
it is the George sub-dataset here: https://huggingface.co/datasets/TencentARC/StoryStream.

**Comment by zzddwyff** [comment]
我就推理需要下载全部的george.zip.gz吗

**Comment by zzddwyff** [comment]
I just excute inference do i need to down load all george.zip.gz?

**Comment by AndysonYs** [comment]
No you don't. You can just take any of the one image-text pair as input.

**Comment by zzddwyff** [comment]
ok let me try try

**Comment by zzddwyff** [comment]
CAN you tell what should i change in your code to inference one image? I find out your code adaptly use lots of images

**Comment by zzddwyff** [comment]
Traceback (most recent call last):
  File "/root/autodl-tmp/SEED-Story/src/inference/gen_george.py", line 213, in <module>
    images_gen = adapter.generate(image_embeds=output['img_gen_feat'], num_inference_steps=50)
  File "/root/autodl-tmp/SEED-Story/src/models_ipa/adapter_modules.py", line 455, in generate
    images = self.sdxl_pipe(
  File "/root/autodl-tmp/conda/envs/seed/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/seed/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 730, in __call__
    ) = self.encode_prompt(
  File "/root/autodl-tmp/conda/envs/seed/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 379, in encode_prompt
    prompt_embeds = prompt_embeds.to(dtype=self.text_encoder_2.dtype, device=device)
AttributeError: 'NoneType' object has no attribute 'dtype'


only one image come out

**Comment by AndysonYs** [comment]
> CAN you tell what should i change in your code to inference one image? I find out your code adaptly use lots of images

Hi. Please see src/inference/gen_george.py. If you want to get a long story given only 1 text-image pair. Then you can change the line 152 to 
`
for j in range(1):
`
and you should make sure the first line of the val.jsonl file is your input.

If you don't even want a long story, you just need it to generate 1 text-image pair. Then you can change the story_len param to 2 in line 205.
